// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDC0Kw0Z2vTQTA5XSebKdMOis7ENddrz_4',
    appId: '1:1073554975104:web:124ce1ba51e18512c27965',
    messagingSenderId: '1073554975104',
    projectId: 'flutter-project-b5a1a',
    authDomain: 'flutter-project-b5a1a.firebaseapp.com',
    storageBucket: 'flutter-project-b5a1a.firebasestorage.app',
    measurementId: 'G-J4YG3Y1W8F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjGgXLJi_XvawtlurcEnIaNHehmoJpDgc',
    appId: '1:1073554975104:android:853885c56473da5ac27965',
    messagingSenderId: '1073554975104',
    projectId: 'flutter-project-b5a1a',
    storageBucket: 'flutter-project-b5a1a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7q9XIAzC2L5UF15DosvyqKSGp_vulgp8',
    appId: '1:1073554975104:ios:8eb64e4d86ebfccfc27965',
    messagingSenderId: '1073554975104',
    projectId: 'flutter-project-b5a1a',
    storageBucket: 'flutter-project-b5a1a.firebasestorage.app',
    iosBundleId: 'com.example.flutterLearning',
  );
}
